{
  "openapi":"3.0.2",
  "info": {
    "title":"Go Commerce",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/gocommerce/main/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/customers": {
      "post": {
        "tags": ["Customers"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email"
                ],
                "title": "Customer",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "John Doe",
                "email": "johndoe@example.com"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new customer",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Customer"
                },
                "example": {
                  "id": "51450dc5-7647-4fa7-877b-fe98e78c2a6c",
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "created_at": "2021-09-01T03:10:41.705Z",
                  "updated_at": "2021-09-01T03:10:41.705Z"
                }
              }
            }
          },
          "400": {
            "description": "The email provided already in use",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "The email provided already in use",
                  "code": 140,
                  "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/customers/{id}": {
      "get": {
        "tags": ["Customers"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "51450dc5-7647-4fa7-877b-fe98e78c2a6c"
          }
        ],
        "responses": {
          "200": {
            "description": "Return one customer",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Customer"
                    },
                    {
                      "title": "Customer",
                      "properties": {
                        "url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "51450dc5-7647-4fa7-877b-fe98e78c2a6c",
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "created_at": "2021-09-01T03:10:41.705Z",
                  "updated_at": "2021-09-01T03:10:41.705Z",
                  "url": "http://localhost:3333/v1/customers/51450dc5-7647-4fa7-877b-fe98e78c2a6c"
                }
              }
            }
          },
          "404": {
            "description": "Customer not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Customer not found",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/products": {
      "post": {
        "tags": ["Products"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "price",
                  "quantity"
                ],
                "title": "Customer",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "price": {
                    "type": "number"
                  },
                  "quantity": {
                    "type": "integer"
                  }
                }
              },
              "example": {
                "name": "Hocks Ibiza",
                "price": 280.90,
                "quantity": 100
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new product",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                },
                "example": {
                  "id": "dee8bd5a-cfc3-40e2-a5f2-bcac1533f5ed",
                  "name": "Hocks Ibiza",
                  "price": 280.9,
                  "quantity": 100,
                  "created_at": "2021-09-01T03:19:14.364Z",
                  "updated_at": "2021-09-01T03:19:14.364Z"
                }
              }
            }
          },
          "409": {
            "description": "A product with the same name already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "A product with the same name already exists",
                  "code": 349,
                  "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "tags": ["Products"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "dee8bd5a-cfc3-40e2-a5f2-bcac1533f5ed"
          }
        ],
        "responses": {
          "200": {
            "description": "Return one customer",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Product"
                    },
                    {
                      "title": "Product",
                      "properties": {
                        "url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "dee8bd5a-cfc3-40e2-a5f2-bcac1533f5ed",
                  "name": "Hocks Ibiza",
                  "price": "280.90",
                  "quantity": 100,
                  "created_at": "2021-09-01T03:19:14.364Z",
                  "updated_at": "2021-09-01T03:19:14.364Z",
                  "url": "http://localhost:3333/v1/products/dee8bd5a-cfc3-40e2-a5f2-bcac1533f5ed"
                }
              }
            }
          },
          "404": {
            "description": "Customer not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Product not found",
                  "code": 344,
                  "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/orders": {
      "post": {
        "tags": ["Orders"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "customer_id",
                  "products"
                ],
                "title": "Order",
                "properties": {
                  "customer_id": {
                    "type": "string"
                  },
                  "products": {
                    "type": "array",
                    "items": {
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "quantity": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "customer_id": "51450dc5-7647-4fa7-877b-fe98e78c2a6c",
                "products": [
                  {
                    "id": "dee8bd5a-cfc3-40e2-a5f2-bcac1533f5ed",
                    "quantity": 5
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new order",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                },
                "example": {
                  "id": "39417e90-73f4-49f4-b30e-324784c9cc60",
                  "customer_id": "51450dc5-7647-4fa7-877b-fe98e78c2a6c",
                  "customer": {
                    "id": "51450dc5-7647-4fa7-877b-fe98e78c2a6c",
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "created_at": "2021-09-01T03:10:41.705Z",
                    "updated_at": "2021-09-01T03:10:41.705Z"
                  },
                  "order_products": [
                    {
                      "id": "3b73bfe2-92eb-4785-abac-bb6570c73d8a",
                      "order_id": "39417e90-73f4-49f4-b30e-324784c9cc60",
                      "product_id": "dee8bd5a-cfc3-40e2-a5f2-bcac1533f5ed",
                      "price": "280.90",
                      "quantity": 5,
                      "created_at": "2021-09-01T03:29:15.394Z",
                      "updated_at": "2021-09-01T03:29:15.394Z"
                    }
                  ],
                  "created_at": "2021-09-01T03:29:15.394Z",
                  "updated_at": "2021-09-01T03:29:15.394Z"
                }
              }
            }
          },
          "400": {
            "description": "Errors while creating a new order",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "Customer not found": {
                    "value": {
                      "status": "error",
                      "message": "Customer not found",
                      "code": 245,
                      "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                    }
                  },
                  "Product not found": {
                    "value": {
                      "status": "error",
                      "message": "Product not found",
                      "code": 246,
                      "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                    }
                  },
                  "There is not enough product quantity in stock": {
                    "value": {
                      "status": "error",
                      "message": "There is not enough product quantity in stock",
                      "code": 240,
                      "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "tags": ["Orders"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "39417e90-73f4-49f4-b30e-324784c9cc60"
          }
        ],
        "responses": {
          "200": {
            "description": "Return the products from an order",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Order"
                    },
                    {
                      "title": "Order",
                      "properties": {
                        "customer": {
                          "type": "object",
                          "properties": {
                            "url": {
                              "type": "string"
                            }
                          }
                        },
                        "order_products": {
                          "type": "array",
                          "items": {
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/OrderProduct"
                              },
                              {
                                "title": "OrderProduct",
                                "properties": {
                                  "product": {
                                    "$ref": "#/components/schemas/Product"
                                  },
                                  "url": {
                                    "type": "string"
                                  }
                                }
                              }
                            ]
                          }
                        },
                        "products_url": {
                          "type": "string"
                        },
                        "url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "9bb67de8-fb7b-40c0-a019-2b8fe73666d4",
                  "customer_id": "4eafed19-079f-4d90-97f1-00846882bbe7",
                  "created_at": "2021-09-01T04:58:56.289Z",
                  "updated_at": "2021-09-01T04:58:56.289Z",
                  "customer": {
                    "id": "4eafed19-079f-4d90-97f1-00846882bbe7",
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "created_at": "2021-09-01T04:56:39.388Z",
                    "updated_at": "2021-09-01T04:56:39.388Z",
                    "url": "http://localhost:3333/v1/customers/4eafed19-079f-4d90-97f1-00846882bbe7"
                  },
                  "order_products": [
                    {
                      "id": "b684c556-cb4c-4c07-90b1-affa4b10acb3",
                      "product_id": "b5759337-767e-401e-bf18-2062186a28e8",
                      "order_id": "9bb67de8-fb7b-40c0-a019-2b8fe73666d4",
                      "price": "280.90",
                      "quantity": 5,
                      "created_at": "2021-09-01T04:58:56.289Z",
                      "updated_at": "2021-09-01T04:58:56.289Z",
                      "product": {
                        "id": "b5759337-767e-401e-bf18-2062186a28e8",
                        "name": "Hocks Ibiza",
                        "price": "280.90",
                        "quantity": 90,
                        "created_at": "2021-09-01T04:57:19.787Z",
                        "updated_at": "2021-09-01T04:58:56.300Z"
                      },
                      "url": "http://localhost:3333/v1/products/b684c556-cb4c-4c07-90b1-affa4b10acb3"
                    }
                  ],
                  "products_url": "http://localhost:3333/v1/orders/9bb67de8-fb7b-40c0-a019-2b8fe73666d4/products",
                  "url": "http://localhost:3333/v1/orders/9bb67de8-fb7b-40c0-a019-2b8fe73666d4"
                }
              }
            }
          },
          "404": {
            "description": "Order not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Order not found",
                  "code": 244,
                  "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/orders/{id}/products": {
      "get": {
        "tags": ["Orders"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "39417e90-73f4-49f4-b30e-324784c9cc60"
          }
        ],
        "responses": {
          "200": {
            "description": "Return the products from an order",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/OrderProduct"
                    },
                    {
                      "title": "OrderProduct",
                      "properties": {
                        "product": {
                          "$ref": "#/components/schemas/Product"
                        },
                        "name": {
                          "type": "string"
                        },
                        "order_url": {
                          "type": "string"
                        },
                        "url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": [
                  {
                    "id": "b684c556-cb4c-4c07-90b1-affa4b10acb3",
                    "product_id": "b5759337-767e-401e-bf18-2062186a28e8",
                    "order_id": "9bb67de8-fb7b-40c0-a019-2b8fe73666d4",
                    "price": "280.90",
                    "quantity": 5,
                    "product": {
                      "id": "b5759337-767e-401e-bf18-2062186a28e8",
                      "name": "Hocks Ibiza",
                      "price": "280.90",
                      "quantity": 90,
                      "created_at": "2021-09-01T04:57:19.787Z",
                      "updated_at": "2021-09-01T04:58:56.300Z"
                    },
                    "name": "Hocks Ibiza",
                    "created_at": "2021-09-01T04:58:56.289Z",
                    "updated_at": "2021-09-01T04:58:56.289Z",
                    "order_url": "http://localhost:3333/v1/orders/9bb67de8-fb7b-40c0-a019-2b8fe73666d4",
                    "url": "http://localhost:3333/v1/products/b5759337-767e-401e-bf18-2062186a28e8"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Order not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "status": "error",
                  "message": "Order not found",
                  "code": 247,
                  "docs": "https://github.com/DiegoVictor/gocommerce#errors-reference"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Customer": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Product": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "number"
          },
          "quantity": {
            "type": "integer"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "OrderProduct": {
        "properties": {
          "id": {
            "type": "string"
          },
          "order_id": {
            "type": "string"
          },
          "product_id": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "quantity": {
            "type": "integer"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Order": {
        "properties": {
          "id": {
            "type": "string"
          },
          "customer_id": {
            "type": "string"
          },
          "customer": {
            "$ref": "#/components/schemas/Customer"
          },
          "order_products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OrderProduct"
            }
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Error": {
        "properties": {
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    }
  }
}
